export const AUTH_SECURITY = {
  ACCESS_TOKEN_EXPIRES_IN_SECONDS: 15 * 60,
  REMEMBER_ME_REFRESH_SESSION_EXPIRES_IN_DAYS: 30,
  STANDARD_REFRESH_SESSION_EXPIRES_IN_DAYS: 1,
  PASSWORD_RESET_TOKEN_EXPIRES_IN_MINUTES: 30,
  EMAIL_VERIFICATION_TOKEN_EXPIRES_IN_HOURS: 24,
  EMPLOYEE_INVITATION_TOKEN_EXPIRES_IN_DAYS: 7,
  RANDOM_TOKEN_BYTES: 32,
} as const;
